//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkileAkbilYönetimiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akbiller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Akbiller()
        {
            this.Talimatlar = new HashSet<Talimatlar>();
        }
    
        public int Id { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string AkbilSahibi { get; set; }
        public string SeriNumarasi { get; set; }
        public Nullable<System.DateTime> GuncellenmeTarihi { get; set; }
        public bool AktifMi { get; set; }
        public decimal Bakiye { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Talimatlar> Talimatlar { get; set; }

        public static bool TumKarakterlerRakamMi(string metin) //IsAllCharacterDigit
        {
            foreach (var item in metin)
            {
                if (!char.IsDigit(item)) // bu karakter digit mi? 
                {
                    return false;
                }
            }

            return true;
        }
    }
}
